name: MLMguru
favicon: null
layout_spectrum: 0.96247
typography_spectrum: 0.93199
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f2224'
    - '#e4e4e4'
    - '#5c4b40'
    - '#4b75ab'
    - '#b9a38a'
  brandStrength: 0.3699946792330593
  lightness: 0.9375
  saturation: 0.25311826216056943
  rhythmicContrast: 0.8870693964418024
purpose: []
